<?php

/**
 * PluginsbLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbLocationTable extends Doctrine_Table
{
	/**
		* Returns an instance of this class.
		*
		* @return object PluginsbLocationTable
		*/
	public static function getInstance()
	{
			return Doctrine_Core::getTable('PluginsbLocation');
	}

	public static function getSlideShowName($location)
	{
		return  'sbLocation-' . $location['id'];
	}

	public static function getSlideShowSlug($location)
	{
		return 'sbLocation-' . $location['id'];
	}

	public static function getFirstImage($location)
	{
		$page = aPageTable::retrieveBySlugWithSlots(self::getSlideShowSlug($location));
    
    if($page)
    {
      $slot = $page->getSlot(self::getSlideShowName($location));

      if($slot)
      {
        $images = $slot->getOrderedMediaItems();

        if($images)
        {
          return $images[0]->getCropOriginal();
        }
      }
    }
			
		return false;
	}
  
  public static function listLocations($params = array())
  {
    $result = Doctrine_Query::create()->from('sbLocation AS l');
    
    if(isset($params['active']))
    {
      $result->andWhere('active = ?', $params['active']);
    }
    
    if(isset($params['order_by']))
    {
      $result->orderBy($params['order_by']);
    }
    else
    {
      $result->orderBy('l.updated_at DESC');
    }
    
    $fast = sfConfig::get('app_a_fasthydrate', false);
    return $result->execute();
  }
  
  /**
	 * Returns an array of sbGoogleSitemapPage objects for use by the google sitemap plugin
	 * @return array
	 */
	public static function pagesForSitemap()
	{
		sfContext::getInstance()->getConfiguration()->loadHelpers(array('Url'));
		$return    = array();
		$locations = self::listLocations(array('active' => true));

		foreach($locations as $location)
		{
			$return[] = new sbGoogleSitemapPage(sfContext::getInstance()->getRequest()->getHost(), url_for('@sb_location?slug=' . $location['slug']), false, 'monthly', 0.8, strtotime($location['updated_at']));
		}

		return $return;
	}
  
  public function addCategoriesForUser(sfGuardUser $user, $admin = false)
  {
    $q = $this->addCategories();  
    return Doctrine::getTable('aCategory')->addCategoriesForUser($user, $admin, $q);
  }

  public function addCategories(Doctrine_Query $q=null)
  {
    if(is_null($q))
      $q = Doctrine::getTable('aCategory')->createQuery();
      
    $q->addOrderBy('aCategory.name');
    return $q;
  }
  
  /**
 * Calculates the great-circle distance between two points, with
 * the Vincenty formula.
 * @param float $latitudeFrom Latitude of start point in [deg decimal]
 * @param float $longitudeFrom Longitude of start point in [deg decimal]
 * @param float $latitudeTo Latitude of target point in [deg decimal]
 * @param float $longitudeTo Longitude of target point in [deg decimal]
 * @param float $earthRadius Mean earth radius in [m]
 * @return float Distance between points in [m] (same as earthRadius)
 */
  public static function vincentyGreatCircleDistance($latitudeFrom, $longitudeFrom, $latitudeTo, $longitudeTo, $earthRadius = 6371000)
  {
    // convert from degrees to radians
  $latFrom = deg2rad($latitudeFrom);
  $lonFrom = deg2rad($longitudeFrom);
  $latTo = deg2rad($latitudeTo);
  $lonTo = deg2rad($longitudeTo);

  $latDelta = $latTo - $latFrom;
  $lonDelta = $lonTo - $lonFrom;

  $angle = 2 * asin(sqrt(pow(sin($latDelta / 2), 2) +
    cos($latFrom) * cos($latTo) * pow(sin($lonDelta / 2), 2)));
  return $angle * $earthRadius;
  }
}