<?php

/**
 * PluginsbLocationToASearchDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbLocationToASearchDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbLocationToASearchDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbLocationToASearchDocument');
    }
}