<?php

/**
 * PluginsbLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsbLocation extends BasesbLocation
{
	public function getSearchText()
	{
		return $this->getTitle() . " " . 
						$this->getDescription() . " " . 
						$this->getMapDescription() . " " . 
						$this->getAddressLine1() . " " . 
						$this->getAddressLine2() . " " . 
						$this->getAddressTownCity() . " " . 
						$this->getAddressCounty() . " " . 
						$this->getAddressPostalCode() . " " . 
						$this->getTelephoneLandline() . " " . 
						$this->getTelephoneMobile() . " " . 
						implode(' ', $this->getTags());
	}

	public function getSummary()
	{
		return $this->getTitle();
	}

	public function postSave($event)
	{
		parent::postSave($event);

		aTools::$searchService->update(
			array(
				'item' => $this,
				'text' => $this->getSearchText(),
				'info' => array('summary' => $this->getSummary()),
				'culture' => aTools::getUserCulture()));
	}

	public function postDelete($event)
	{
		parent::postDelete($event);

		aTools::$searchService->delete(
			array(
				'item' => $this
			)
		);
	}
}