<?php

/**
 * PluginsbSingleLocationMapSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbSingleLocationMapSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbSingleLocationMapSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbSingleLocationMapSlot');
    }
}