generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sbLocation
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sb_location_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        active: { help: "Only active locations will appear on the website" }
        geocode_latitude: { label: Lat }
        geocode_longitude: { label: Lon }
        address_town_city: { label: "Town/City" }
        address_county: { label: "County" }
        address_country: { label: "Country" }
        updated_at: { label: Last Updated }
      
      list:
        title: Locations Admin
        display: [ title, active, address_town_city, address_county, address_state, address_country, updated_at ]
        sort: [ title ]
        actions:
          new:
            label: New Location
            action: new
            params:
              class: a-btn big icon a-add
        
      filter:  
        fields:   [ title, active ]
        display:  [ title, active ]
      form:    ~
      
      edit:
        title: "Edit Location"
        display: 
          Location Details: [ title, active, categories_list, _descriptions ]
          Contact Details: [ telephone_landline, telephone_mobile, website_url, email_address ]
          Address: [ _address ]
          Tags: [ tags ]
          
        
      new:
        title: Add Location
        display: 
          Location Details: [ title, active, categories_list, _descriptions ]
          Contact Details: [ telephone_landline, telephone_mobile, website_url, email_address ]
          Address: [ _address ]
          Tags: [ tags ]
