sb_location_admin:
  class: sfDoctrineRouteCollection
  options:
    model:                sbLocation
    module:               sbLocationsAdmin
    prefix_path:          /admin/sb-locations
    column:               id
    with_wildcard_routes: true
    collection_actions:
      new_with_title: post
      
sb_location_redirect:
  url: /sbLocation/:id
  param: { module: sbLocationsAdmin, action: redirect }
  options: { model: sbLocation, type: object }
  class: sfDoctrineRoute
    
sb_locations_lookup:
  url: /sb-locations-lookup/:lookup/:address
  params: { module: sbLocationsLookup, action: lookup }
  requirements: { lookup: '[\w-]+' }
  
sb_locations_map_list:
  url: /sb-locations-map-list
  params: { module: sbLocationsLookup, action: mapList }
  
sb_locations:
  url: /
  params: { module: sbLocations, action: index }
  class: aRoute
  
sb_location:
  url: /:slug
  params: { module: sbLocations, action: location }
  options: { model: sbLocation, type: object }
  class: aDoctrineRoute
  requirements: { slug: '[\w-]+' }