default:
  stylesheets:
    - /sbApostropheLocationsPlugin/css/sb-locations.css: { data-asset-group: global }
  javascripts:
    - /sbApostropheLocationsPlugin/js/sb-locations.js: { data-asset-group: global }
    - https://maps.google.com/maps/api/js?sensor=false: { data-asset-group: global }